### ISSUE TITLE
Setting env on script does not work

### ISSUE THREAD

**Issue by ovidijusr** [s00d/webpack-shell-plugin-next#7]
When trying to execute script with env variables it gives me error
```javascript
new WebpackShellPlugin({
          onBuildEnd: {
            scripts: [`foo=bar echo 'hello world'`],
          },
        }),
```

Gives

```
Error: spawn foo=bar ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by s00d** [comment]
hello. added env variable
